#!/usr/bin/bash
virtualenv ../.env
source .env/bin/activate
pip install -r ./neuralcoref/requirements.txt
pip install -e ./neuralcoref
python3 -m spacy download en_core_web_sm
pip install nltk numpy networkx pandas tqdm matplotlib scipy
python3 -c "import nltk; nltk.download('stopwords')"